version: "3.6"
services:
  postgres:
    image: postgres
    container_name: pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  yellow_express:
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
    container_name: yellow_express
    build:
      dockerfile: express.dockerfile
      context: .
      args:
        - EXPRESS_PORT=${EXPRESS_PORT}
    restart: always
    environment:
      - EXPRESS_PORT=${EXPRESS_PORT}
      - HASURA_ACTION_SECRET=${HASURA_ACTION_SECRET}
      - NODE_ENV=${NODE_ENV:-development}
  yellow_graphql_engine:
    container_name: yellow_graphql_engine
    ports:
      - ${HASURA_GRAPHQL_SERVER_PORT}:${HASURA_GRAPHQL_SERVER_PORT}
    image: hasura/graphql-engine:v2.30.1
    restart: always
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${POSTGRES_URI}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_ACTION_SECRET: ${HASURA_ACTION_SECRET}
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_SERVER_PORT: ${HASURA_GRAPHQL_SERVER_PORT}
      HASURA_GRAPHQL_DEV_MODE: "true"
      ACTION_BASE_URL: ${ACTION_BASE_URL}

volumes:
  pgdata:
